### ISSUE TITLE
Start-Process Clobber

### ISSUE THREAD

**Issue by BClev** [adamdriscoll/PoshInternals#11]
When installing from Powershell Gallery, the module clobbers with the existing Powershell command "Start-Process", and so the install errors out. Looking at your code, I don't see any function or command called "Start-Process" that differs from the standard Powershell one.

**Comment by mavericksevmont** [comment]
This seems to be by-design, not a problem! It is ok to clobber, it will just add parameters and other functionality to the already existing commandlet, e.g. "Desktop"
