### ISSUE TITLE
PowerShell With VS 2017

### ISSUE THREAD

**Issue by AbuAlAwad** [adamdriscoll/PoshInternals#12]
Hi All, 
I Created a new PowerShell Script project. I'm Getting the error  "Attaching the PowerShell Debug Engine debugger to process '{[<GUID>']} on machine <machineName> failed."  When trying to execute an Empty PowerShell. Any Idea how to fix this?

**Comment by adamdriscoll** [comment]
Please open an issue at https://www.poshtools.com/issues
