### ISSUE TITLE
Start-RemoteProcess as `nt authority\system`

### ISSUE THREAD

**Issue by alx9r** [adamdriscoll/PoshInternals#6]
Hi @adamdriscoll,
[I'm trying to get `nt authority\system` processes working over PowerShell remoting.](https://stackoverflow.com/questions/33558772/is-it-possible-to-start-a-process-as-nt-authority-system-over-powershell-remot) and [I came across](http://csharpening.net/?p=1572) [PoshExec.ps1](https://github.com/adamdriscoll/PoshInternals/blob/ee067bfd0f5f7238b686528a191bc51ac6679507/PoshExec.ps1).  It looks to me that `Start-RemoteProcess` doesn't _currently_ support starting a process as `nt authority\system`.  Is that correct?  If so, do you have a general idea of what would be involved to get that working?  I'm just trying to get a sense of the scope of that work so I can figure out whether this is a good way to solve my problem.

Thanks for your help, 

Alex

**Comment by adamdriscoll** [comment]
Hey @alx9r, 

I'm not quite sure exactly. I imagine the service needs to be set to run as system when it's created. It really shouldn't be all that difficult but I'd have to revisit this code to determine scope because I haven;'t look at it in quite some time.

**Comment by alx9r** [comment]
Oh I see now.  It even [looks like `sc.exe` starts processes as "LocalSystem" by default](https://technet.microsoft.com/en-ca/library/bb490995.aspx), so I'm guessing that `Start-RemoteProcess` already starts processes as `nt authority\System` in the same way as other "LocalSystem" services seem to do.

Thanks for your help @adamdriscoll
